"""initial

Revision ID: 4a9a4ce10c38
Revises: 
Create Date: 2026-09-18 12:42:36

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a9a4ce10c38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regexes')
    op.drop_table('source__regex101')
    op.drop_table('alembic_version')
    op.drop_table('source__regexlib')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source__regexlib',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pattern', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('matching_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('non_matching_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_dirty', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source_date_modified', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('source__regexlib_pkey'))
    )
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.create_table('source__regex101',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('regex', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('flags', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('delimiter', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dialect', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('source__regex101_pkey'))
    )
    op.create_table('regexes',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('regex', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('params', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('regex_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('regexes_pkey'))
    )
    # ### end Alembic commands ###
