"""empty message

CRED MIGRATIONS

Revision ID: 81450d4b0971
Revises: 
Create Date: 2026-09-19 10:37:05

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '81450d4b0971'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regexes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('regex', sa.String(), nullable=False),
    sa.Column('regex_id_in_source', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('regex_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('source__regex101',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('permalink', sa.String(), nullable=False),
    sa.Column('regex', sa.String(), nullable=False),
    sa.Column('flags', sa.String(), nullable=True),
    sa.Column('delimiter', sa.String(), nullable=False),
    sa.Column('dialect', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permalink'),
    schema='public'
    )
    op.create_table('source__regexlib',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('pattern', sa.String(), nullable=False),
    sa.Column('matching_text', sa.String(), nullable=False),
    sa.Column('non_matching_text', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('is_dirty', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('source_date_modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.drop_table('source__regexlib', schema='public')
    op.drop_table('source__regex101', schema='public')
    op.drop_table('regexes', schema='public')
    # ### end Alembic commands ###
